---
:last_used_folder: C:\Users\Leo\VSCodeProjects\cdos-traducao-ptbr\Extracted files
  Castlevania - Alvor da Tristeza (BR)
:tiled_path: ''
:emulator_path: C:/Users/Leo/Emuladores/nds/melonDS/melonDS.exe
:gba_emulator_path: ''
:test_room_save_file_index: 0
